
import Head from 'next/head'
import Image from 'next/image'
import Landpage1 from '../components/landpage1'
import LandPage from '../components/LandPage'
import Hero from '../components/hero'
import Hero2 from '../components/hero2'
import Work from '../components/work'
import Car from '../components/carousel'
import Footer from '../components/footer'
import 'bootstrap/dist/css/bootstrap.css'
import Navbar1 from '../components/navbar'
import {Nav,Navbar, NavDropdown, Button, Carousel, Col, Row, Container , Card,Form, ListGroup, NavLink} from 'react-bootstrap'
import {location} from '../public/location.svg'


function app(){
  return(
    <div>
      <Head>
        <title>Weza.org</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png "  width={15} height={15}/>
        
        {/* <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;500&display=swap" rel="stylesheet"></link> */}
      
       <link rel="preconnect" href="https://fonts.googleapis.com"></link>
       <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin></link>

       <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700&family=Raleway:wght@900&display=swap" rel="stylesheet"></link>



      
        </Head>
      <div className='app'>
      <Navbar1/>
      <LandPage/>
      <Hero/>
      <Hero2/>
      <Work/>
      <Footer/>
      
    </div>
    </div>
    
  );
}
export default app;